# Generated by Django 3.1.7 on 2021-04-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210410_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='dicount_percentage',
            new_name='discount_percentage',
        ),
    ]
