# Generated by Django 3.1.7 on 2021-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210410_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='discount_price',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
