# Generated by Django 3.1.7 on 2021-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5000)),
                ('last_name', models.CharField(max_length=5000)),
                ('email', models.CharField(max_length=5000)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
