# Generated by Django 3.1.7 on 2021-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_commentsss'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsss',
            name='reply_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
