# Generated by Django 3.1.7 on 2021-04-24 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_auto_20210421_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_id', models.IntegerField(blank=True)),
                ('reply_id', models.IntegerField(blank=True, default=0)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.addproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
